exclude: ^(requirements|.*assets|.*resources|.*results)
default_stages: [ commit ]
repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        stages: [ commit ]
      - id: trailing-whitespace
        stages: [ commit ]
      - id: check-merge-conflict
      - id: double-quote-string-fixer

  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-3
    hooks:
      - id: shfmt
        args: [ --indent, '2', --write ]
        stages: [ commit ]

  - repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
      - id: checkmake
        args: [ --config, './.checkmake.ini' ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
          --multi-line, 'VERTICAL_HANGING_INDENT',
          --trailing-comma,
          --line-length, '120'
        ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [
          --skip-string-normalization,
          --skip-magic-trailing-comma,
          --line-length, '120',
          --target-version, 'py36'
        ]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [ -ll ]

  - repo: https://github.com/pycqa/pylint
    rev: v2.13.9
    hooks:
      - id: pylint
        args: [
          --min-public-methods, '1',
          --disable, 'missing-module-docstring,missing-class-docstring,missing-function-docstring,import-error,duplicate-code',
          --max-line-length, '120',
          --py-version, '3.6'
        ]
