exclude: ^(requirements|.*assets|.*resources|.*results)
default_stages: [ commit ]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        stages: [ commit ]
      - id: trailing-whitespace
        stages: [ commit ]
      - id: check-merge-conflict
      - id: double-quote-string-fixer

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
            '--multi-line', 'VERTICAL_HANGING_INDENT',
            '--trailing-comma',
            '--line-length', '120'
        ]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [
            '--skip-string-normalization',
            '--skip-magic-trailing-comma',
            '--line-length', '120'
        ]

  - repo: https://github.com/pycqa/pylint
    rev: v2.15.3
    hooks:
      - id: pylint
        args: [
            '--max-line-length', '120',
            '--min-public-methods', '1',
            '--disable', 'missing-module-docstring,missing-class-docstring,missing-function-docstring,import-error'
        ]

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ['-ll']
